import { Geist, Geist_Mono, IBM_Plex_Sans, Montserrat } from "next/font/google";
import "./globals.css";
import { Provider } from "./provider";
const ibm = IBM_Plex_Sans({
  variable: "--font-ibm",
  subsets: ["latin"],
});
const monster = Montserrat({
  variable: "--font-most",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${ibm.className} ${monster.variable} antialiased selection:bg-teal-500 selection:text-black`}
      >
        <Provider
          
        >
          {children}
        </Provider>
      </body>
    </html>
  );
}
